# Generated by Django 6.0.8 on 2026-08-17 22:06

import django.core.validators
import django.db.models.deletion
import journals.models
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doi", models.CharField(db_index=True, max_length=64, unique=True)),
                ("title", models.TextField(blank=True)),
                (
                    "authors",
                    models.TextField(
                        blank=True, help_text="Display string, comma separated."
                    ),
                ),
                ("article_type", models.CharField(blank=True, max_length=64)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("metadata_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["doi"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="JournalIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="JournalPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "journal_key",
                    models.SlugField(
                        help_text="DOI component, e.g. 'pmed' for PLOS Medicine.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="VolumeIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(journals.models.TreePositionMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="VolumePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Volume number, e.g. 18. Drives the DOI and ordering."
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Left blank, this is generated from the journal key and volume number.",
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^10\\.1371/volume\\.[a-z]+\\.v\\d{2}$",
                                "Expected e.g. 10.1371/volume.pmed.v18",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(journals.models.TreePositionMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="IssuePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Issue number within the volume, 1–12."
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Left blank, this is generated from the volume DOI and issue number.",
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^10\\.1371/issue\\.[a-z]+\\.v\\d{2}\\.i\\d{2}$",
                                "Expected e.g. 10.1371/issue.pmed.v18.i02",
                            )
                        ],
                    ),
                ),
                (
                    "image_article_doi",
                    models.CharField(
                        blank=True,
                        help_text="Left blank, derived from the issue DOI (issue. → image.). Used as the cover's link target, not as the image source.",
                        max_length=64,
                    ),
                ),
                (
                    "cover_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to fall back to the image's own default alt text.",
                        max_length=255,
                    ),
                ),
                (
                    "cover_caption",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="The 'About this image' text shown on the archive and issue pages.",
                    ),
                ),
                ("cover_credit", models.CharField(blank=True, max_length=255)),
                (
                    "bulk_dois",
                    models.TextField(
                        blank=True,
                        help_text="Paste article DOIs, one per line. They are added to the list below on save and this box is cleared. Order does not matter — the table of contents is grouped by article type and sorted by date.",
                        verbose_name="Add articles by DOI",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        help_text="Issue cover. Required to publish.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
            bases=(journals.models.TreePositionMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="JournalSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_issue",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to use the most recent published issue.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="journals.issuepage",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal settings",
            },
        ),
        migrations.CreateModel(
            name="IssueArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_entries",
                        to="journals.article",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_articles",
                        to="journals.issuepage",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "article")},
            },
        ),
    ]
