# Generated by Django 6.0.8 on 2026-08-17 23:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalpage",
            name="billboard",
            field=wagtail.fields.StreamField(
                [("article", 6), ("link", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("journals.Article",),
                        {
                            "help_text": "Search by DOI, title or author. New DOIs can be added from Snippets → Articles."
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's type, e.g. 'Research Article'.",
                            "label": "Subject",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's own title.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The homepage summary. Written for the homepage, so it is never derived from the abstract.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("article", 0),
                                ("kicker", 1),
                                ("headline", 2),
                                ("teaser", 3),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subject", "max_length": 64, "required": False},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    10: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 7),
                                ("kicker", 8),
                                ("headline", 9),
                                ("teaser", 10),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="The banner under the hero. The headline and teaser are the banner's heading and description.",
            ),
        ),
        migrations.AddField(
            model_name="journalpage",
            name="hero",
            field=wagtail.fields.StreamField(
                [("article", 6), ("link", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("journals.Article",),
                        {
                            "help_text": "Search by DOI, title or author. New DOIs can be added from Snippets → Articles."
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's type, e.g. 'Research Article'.",
                            "label": "Subject",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's own title.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The homepage summary. Written for the homepage, so it is never derived from the abstract.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("article", 0),
                                ("kicker", 1),
                                ("headline", 2),
                                ("teaser", 3),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subject", "max_length": 64, "required": False},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    10: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 7),
                                ("kicker", 8),
                                ("headline", 9),
                                ("teaser", 10),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="The full-width slot at the top. Needs an image; the headline is the text laid over it.",
            ),
        ),
        migrations.AddField(
            model_name="journalpage",
            name="tier_one",
            field=wagtail.fields.StreamField(
                [("article", 6), ("link", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("journals.Article",),
                        {
                            "help_text": "Search by DOI, title or author. New DOIs can be added from Snippets → Articles."
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's type, e.g. 'Research Article'.",
                            "label": "Subject",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's own title.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The homepage summary. Written for the homepage, so it is never derived from the abstract.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("article", 0),
                                ("kicker", 1),
                                ("headline", 2),
                                ("teaser", 3),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subject", "max_length": 64, "required": False},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    10: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 7),
                                ("kicker", 8),
                                ("headline", 9),
                                ("teaser", 10),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Tier 1",
            ),
        ),
        migrations.AddField(
            model_name="journalpage",
            name="tier_three",
            field=wagtail.fields.StreamField(
                [("article", 6), ("link", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("journals.Article",),
                        {
                            "help_text": "Search by DOI, title or author. New DOIs can be added from Snippets → Articles."
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's type, e.g. 'Research Article'.",
                            "label": "Subject",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's own title.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The homepage summary. Written for the homepage, so it is never derived from the abstract.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("article", 0),
                                ("kicker", 1),
                                ("headline", 2),
                                ("teaser", 3),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subject", "max_length": 64, "required": False},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    10: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 7),
                                ("kicker", 8),
                                ("headline", 9),
                                ("teaser", 10),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Tier 3",
            ),
        ),
        migrations.AddField(
            model_name="journalpage",
            name="tier_two",
            field=wagtail.fields.StreamField(
                [("article", 6), ("link", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("journals.Article",),
                        {
                            "help_text": "Search by DOI, title or author. New DOIs can be added from Snippets → Articles."
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's type, e.g. 'Research Article'.",
                            "label": "Subject",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the article's own title.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The homepage summary. Written for the homepage, so it is never derived from the abstract.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("article", 0),
                                ("kicker", 1),
                                ("headline", 2),
                                ("teaser", 3),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subject", "max_length": 64, "required": False},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    10: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 7),
                                ("kicker", 8),
                                ("headline", 9),
                                ("teaser", 10),
                                ("image", 4),
                                ("image_credit", 5),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Tier 2",
            ),
        ),
    ]
